### ISSUE TITLE
Is debugging supported?

### ISSUE THREAD

**Issue by jonchase** [bmuschko/gradle-tomcat-plugin#11]
I typically launch a Tomcat instance for remote debugging using an Ant task like this:

``` xml
    <target name="tomcat.debug">
        <java jar="${tomcat.home}/bin/bootstrap.jar" fork="true">
            <jvmarg value="-Dcatalina.home=${tomcat.home}" />
            <jvmarg value="-XX:MaxPermSize=256m" />
            <jvmarg value="-Xdebug" />
            <jvmarg value="-Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n" />
        </java>
    </target>
```

Does the Tomcat plugin support remote debugging?

Cheers,
Jon

**Comment by artemik** [comment]
Command line way doesn't work:
...
* What went wrong:          
Problem configuring task :tomcatRun from command line.
> Unknown command-line option '-X'.

**Comment by bmuschko** [comment]
@artemik Minus capital X (`-X`) is not a valid command line option for Gradle in general. What exactly are you referring to? If you want to set JVM parameters, you'd have to use a different notation e.g. `-Dorg.gradle.jvmargs=-Xdebug`. For more info see [Gradle user guide](https://docs.gradle.org/current/userguide/gradle_command_line.html).

**Comment by artemik** [comment]
Well, but you wrote this in one line:
`gradle tomcatRun -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n`
I'm not an expert in Gradle, that's why i came here, and this line misleads me. Anyway, the documentation says that this parameters should be set in `GRADLE_OPTS` which is not actually a good way for a few reasons:

1. This won't work properly in case of several different Gradle project instances running, since they all will try to listen to the port set in `GRADLE_OPTS`.
2. This won't work with turned on Gradle Daemon. Since Gradle Daemon is a new JVM instance, those properties don't apply to it. For this case there are `org.gradle.jvmargs=...`. If you set those jvm options via this property, it will work in both Daemon On and Daemon Off ways, because if Daemon is Off, Gradle will anyway see that you've set some properties and fork a new jvm for you (which it will notice you about), and if Daemon is On, this property (containing jvm options) will be applied to the Daemon instance.

By the way, when you use set jvm options via  `org.gradle.jvmargs=...` you won't see `Listening for transport dt_socket at address: 5005` message.

I suggest you mention these points in the documentation.

**Comment by bmuschko** [comment]
@artemik 

> Well, but you wrote this in one line.

I was wrong. It happens.

What you really wanted is a forked process that allows you to dedicatedly provide JVM arguments. At the moment the plugin does not provide a forked option. The embedded container runs in the same JVM as Gradle. Please see issue #58 for more details. I'd be happy to integrate a pull request. I am waiting for the community to provide it.

All other questions you have are not necessarily related to this plugin. You'd have the same issue with any other plugin that doesn't work. I'd suggest you ask those questions on the [Gradle forum](https://discuss.gradle.org/).

**Comment by artemik** [comment]
I don't quite understand.
Why can't you specify needed jvm options in `org.gradle.jvmargs`? This options are applied to both the Gradle Daemon (if on) and forked jvm instance, which gradle creates if you specify any `org.gradle.jvmargs` with Daemon turned off.  And, as per your plugin, tomcat would run inside one of these instances, depending on daemon on/off option, if you specify any `org.gradle.jvmargs`.
