### ISSUE TITLE
Need example demonstrating use of compiled JSPs

### ISSUE THREAD

**Issue by cosmocracy** [bmuschko/gradle-tomcat-plugin#145]
Can the documentation please include an example of using the generated *.java output of the tomcatJasper task? Presumably the goal of the task is to allow for the *.java files to be compiled into *.class and used by tomcatRun?

**Comment by bmuschko** [comment]
This functionality is mostly meant to be used for production purposes. You want to precompile your JSPs so that initial loading of web pages upon first hit doesn't require compilation on the server. I guess you could use this for local development but I don't see a point in doing so as you'd add more time for compilation with every restart of the embedded Tomcat server. What's the specific use case you are trying to solve?

**Comment by cosmocracy** [comment]
In our case we have several JSP fragments that we reuse. It would be handy to have access to the intermediate .java files and the compilation results to evaluate/troubleshoot errors in the fragments (or their inclusion).

**Comment by bmuschko** [comment]
I am pretty sure you can make it work by reconfiguring the classpath property of the Tomcat Run task and hooking in the Jasper task as task dependency. The values you'd assign somewhat depend on your project setup. I'd suggest you have a look at the Javadocs of the [TomcatRun](http://bmuschko.github.io/gradle-tomcat-plugin/docs/groovydoc/com/bmuschko/gradle/tomcat/tasks/TomcatRun.html) task.

**Comment by bmuschko** [comment]
I am going to close this issue as you haven't provided additional information. Feel free to reopen if you can provide a sample project that demonstrates your requirements.
