### ISSUE TITLE
Support for executable war

### ISSUE THREAD

**Issue by ctmay4** [bmuschko/gradle-tomcat-plugin#52]
I am converting a project from Maven to Gradle and noticed that the gradle-tomcat-plugin does not support creation of an executable war like Maven does.  Here is the documentation for the Maven plugin support:

http://tomcat.apache.org/maven-plugin-trunk/executable-war-jar.html

Any chance the Gradle plugin could support this as well?

**Comment by alan-czajkowski** [comment]
@bmuschko @ctmay4 @baron1405 wow! the struggle is real!

first, thanks @baron1405 for the initial steps on trying to get this to work with Gradle (was not fun, I had to tweak your code a bit to get it to properly work but it wasn't fun)

i think creating a Gradle plugin that is the equivalent to the Maven Tomcat Plugin (version 2.3-SNAPSHOT) would be of great value to many developers, especially since many places are moving to containerization and the simpler the build the better for everybody (example: if i only need to drop an executable JAR into my Docker container then it simplifies my container quite a bit! no need for Apache Tomcat provisioning inside the container, etc.)

i would be willing to contribute to developing this plugin as it is of great value to me, anybody willing to help?

**Comment by viralshingala** [comment]
**@bmuschko** : Right now for what i need to do for executable war like maven? _Is there any way?_

**Comment by alan-czajkowski** [comment]
@viralshingala yeah, switch to Maven! seriously, the Gradle ecosystem is simply too painful to use ... and while you're at it (switching to Maven), look into using the Spring Boot Maven plugin: https://spring.io/guides/gs/spring-boot/
